services:
  gridscope:
    build: .
    container_name: gridscope_system
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./dados:/app/dados
      - ./logs:/app/logs
      - ./.env:/app/.env
      - .:/app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/gridscope_local

  db:
    image: postgis/postgis:15-3.3
    container_name: gridscope_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gridscope_local
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: gridscope_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
